#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ARRCTL_BIN="${ARRCTL_BIN:-${REPO_DIR}/bin/arrctl}"
TMP_COMPLETION="$(mktemp)"
TMP_HOME=""
TMP_HOME_ZSH=""
trap 'rm -f "$TMP_COMPLETION"; [ -n "$TMP_HOME" ] && rm -rf "$TMP_HOME"; [ -n "$TMP_HOME_ZSH" ] && rm -rf "$TMP_HOME_ZSH"' EXIT
"$ARRCTL_BIN" completion bash > "$TMP_COMPLETION"

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

grep -q '__start_arrctl' "$TMP_COMPLETION" || fail "bash completion output should define __start_arrctl"
grep -q 'complete .*__start_arrctl arrctl' "$TMP_COMPLETION" || fail "bash completion output should register arrctl"

# Install command should be idempotent
TMP_HOME="$(mktemp -d)"

HOME="$TMP_HOME" SHELL="/bin/bash" "$ARRCTL_BIN" completion --install >/dev/null
HOME="$TMP_HOME" SHELL="/bin/bash" "$ARRCTL_BIN" completion --install >/dev/null

[ -f "$TMP_HOME/.bash_profile" ] || [ -f "$TMP_HOME/.bashrc" ] || fail "completion install should create bash profile file"
profile="$TMP_HOME/.bash_profile"
[ -f "$profile" ] || profile="$TMP_HOME/.bashrc"

count="$(grep -c "# >>> arrctl completion >>>" "$profile" || true)"
[ "$count" -eq 1 ] || fail "completion block should be added once (idempotent)"

# Zsh install should write generated completion file and configure fpath
TMP_HOME_ZSH="$(mktemp -d)"

HOME="$TMP_HOME_ZSH" SHELL="/bin/zsh" "$ARRCTL_BIN" completion --install >/dev/null
HOME="$TMP_HOME_ZSH" SHELL="/bin/zsh" "$ARRCTL_BIN" completion --install >/dev/null

zsh_profile="$TMP_HOME_ZSH/.zshrc"
[ -f "$zsh_profile" ] || fail "completion install should create .zshrc for zsh"
[ -f "$TMP_HOME_ZSH/.zsh/completions/_arrctl" ] || fail "zsh completion file should be generated into ~/.zsh/completions"
grep -q '^#compdef arrctl' "$TMP_HOME_ZSH/.zsh/completions/_arrctl" || fail "zsh completion file should be generated by the Go CLI"

grep -q "fpath=(\"$TMP_HOME_ZSH/.zsh/completions\" \$fpath)" "$zsh_profile" || fail "zsh profile should add completion dir to fpath"
grep -q 'autoload -Uz compinit' "$zsh_profile" || fail "zsh profile should autoload compinit"

grep -q 'compinit' "$zsh_profile" || fail "zsh profile should call compinit"

count="$(grep -c "# >>> arrctl completion >>>" "$zsh_profile" || true)"
[ "$count" -eq 1 ] || fail "zsh completion block should be added once (idempotent)"

echo "PASS: completion tests"
